[tool.poetry]
name = "tocot"
version = "0.1.6"
description = "Table Of Contents wO Tsukuru"
readme = "README.md"
license = "MIT"
authors = ["dondakeshimo <went.went.takkun135@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
yapf = "^0.30.0"
isort = "^5.6.4"

[tool.poetry.scripts]
tocot = "tocot.main:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

