[tool.poetry]
name = "pycoloram"
version = "1.0.3"
description = "Модуль для работы с цветным текстом"
authors = ["amfili <amfili.com@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
